# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure for Students(6a8ec4af-e22e-4d6a-9844-0db7db51dd9c)'
    azureContainerRegistry: '{"loginServer":"acrexpensetracker.azurecr.io", "id" : "/subscriptions/6a8ec4af-e22e-4d6a-9844-0db7db51dd9c/resourceGroups/rg-expenseTracker/providers/Microsoft.ContainerRegistry/registries/acrexpensetracker"}'
    dockerComposeFile: '**/docker-compose.yml'
    dockerComposeFileArgs: 'TELEGRAM_BOT_TOKEN=609830348:AAEP9hWQnR6aNbLyoMCRl7BlxpQSqzixwbo'
    action: 'Run a Docker Compose command'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml