services:
  #frontend:
  #  build:
   #   context: "./frontend/events"
    #  dockerfile: "./Dockerfile"
   # networks:
    #  - events_net
  backend:
    build: ./backend
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes: 
      - ".:/usr/src/app/"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*