name: Deploy in Production
on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
  
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v2
        
    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: 22
        script: |                            
          docker compose up -d --build       
    
    - name: Dump docker logs
      uses: jwalton/gh-docker-logs@v1
