name: Deploy in Production
on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v2
        
    - name: Deploy via SSH action
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        port: 22
        script: |                     
          cd expense-tracker
          docker compose up -d --build       
    
    - name: Dump docker logs
      uses: jwalton/gh-docker-logs@v1
